### PR TITLE
ASM event handler

### PR DESCRIPTION
**Pull request by ghost**
Hey cats! Noticed a while ago that attendence was looking a bit slow compared to the gold standard of event managers' speed, BCES. Here's a PR to signifcantly improve speed in dispatchment, (20x).
I'll list through all the changes:

- Introduced IDispatcher
- Renamed EventManager to IEventManager to follow convention
- Removed Checkless event managers, felt it was a micro-optimisation
- Attenders themselves check if they should execute
- Attenders are set to not attend instead of being removed from a map
- A table switch dispatcher is generated via ASM
- Dispatch method is no longer synchronized

All in all, this increases speed significantly, 20x, however to get less than 50x slower than BCES, a redesign to use annotated methods is required, rather than the field Attender objects which the JIT can't optimise enough

PS. could you make a `asm` branch for me to pull request to instead please

### CODE REVIEW

**Comment by ghost** [comment]
@Cuhnt i'll ping you, since you ain't following this repo

**Comment by Cuhnt** [comment]
A few requests before I merge:

1. Add a different manager for asynchronous event managing. A few different places this is used could break without async support. 
2. Don't use the I prefix for interfaces, it's a forge thing that doesn't really make much sense for reading the code. I know this is a bit picky, but I really prefer without the "I" prefix. 

Although not important to this, I was planning on eventually swapping the managers to an abstract class.

**Comment by ghost** [comment]
:crab:

**Comment by Cuhnt** [comment]
🦀

**Pull request merged**
